In [1]:
import numpy as np
x = np.random.randint(1,51,size=(3,3))
print(x)

[[29  4 42]
 [22 39  5]
 [16  8 16]]


In [2]:
np.random.seed(10)
x = np.random.randint(1,51,size=(3,3))
print(x)

[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [3]:
x = np.random.randint(1,51,size=(3,3))
print(x)

[[30 50  9]
 [10  1 43]
 [41 37 17]]
